### ISSUE TITLE
Firefox addon delisted

### ISSUE THREAD

**Issue by timharek** [freshreader/browser-extension#2]
It seems the Firefox addon has been delisted from their addons-page. I cannot find the addon with the link provided on Freshreaders website nor the on in the README.

**Comment by maximevaillancourt** [comment]
Thank you for opening this issue, Tim.

Apologies - I deleted the Mozilla account with which the extension was published, thus (accidentally) removing it from the Firefox add-ons catalog. :facepalm: 

I have submitted the extension at the same URL. It is now awaiting a review from Mozilla, and should be available in the coming days at the URL provided in the website and in this repo's README. I'll update this issue once it's available again. Sorry for the trouble!

**Comment by timharek** [comment]
It's up again now! 😄
